### PR TITLE
Use jscrambler@1.1.8

### LINKED ISSUE #5: peer dep missing
Module `gulp-jscrambler` depends on `jscrambler`, which depends on `grunt-contrib-clean`, which depends on `grunt`.
Command `npm shrinkwrap` fails when `grunt` is not installed. Who would want Grunt, when installing Gulp plug-in?

### PR DESCRIPTION
**Pull request by CodeMan99**
Fixes #5

### CODE REVIEW

**Comment by CodeMan99** [comment]
I also added a "compatible with version" caret range since version locking and shrinkwrapping are becoming the norm.

**Comment by CodeMan99** [comment]
@CMatias Should I go ahead and bump this to `jscrambler@1.2.2`?

**Comment by CMatias** [comment]
@CodeMan99 Thanks for the PR. We're currently discussing how we should manage version since we want to have the packages which rely on `jscrambler` to always have the same version. So I'm going to leave this open for now.

**Comment by CodeMan99** [comment]
@CMatias closing in favor of #9.

**Pull request closed without merging**
